In [1]:
2 * 2

4

In [3]:
# This is a reference

In [ ]:
# test test

In [2]:
print("Hello World")

Hello World


### This is a title 3

In [1]:
import requests

2**5

## Hands On

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
b = np.array([0,0.5,1,1.5,2])

In [7]:
a[0],a[1]

(1, 2)

## Array Types

In [8]:
a

array([1, 2, 3, 4])

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [15]:
np.array([1,2,3,4], dtype = float)

array([1., 2., 3., 4.])

In [16]:
c = np.array(['a','b','c'])

In [17]:
c.dtype

dtype('<U1')

In [19]:
d = np.array([{'a':1},sys])

In [20]:
d.dtype

dtype('O')

## Dimensions and shapes

In [21]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [22]:
A.shape

(2, 3)

In [23]:
A.ndim

2

In [24]:
A.size

6

In [25]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [26]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [27]:
B.shape

(2, 2, 3)

In [28]:
B.ndim

3

In [29]:
B.size

12

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [31]:
A[1]

array([4, 5, 6])

In [32]:
A[1][0]

4

In [33]:
A[1,0]

4

In [34]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
A[2] = 99

In [36]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

## Summary Statistic

In [38]:
A.sum()

318

In [ ]:
A.mean()

35.333333333333336

In [41]:
A.std()

45.04072231510799

In [42]:
A.sum(axis=0)

array([104, 106, 108])

In [43]:
A.std(axis=0)

array([45.50702022, 45.03578824, 44.56455991])

In [44]:
A.mean(axis=1)

array([ 2.,  5., 99.])

## Broadcasting and Vectorized operations

In [48]:
a

array([1, 2, 3, 4])

In [50]:
a = np.arange(4)

In [51]:
a

array([0, 1, 2, 3])

In [52]:
a*10

array([ 0, 10, 20, 30])

In [53]:
a+10

array([10, 11, 12, 13])

In [54]:
a+=10

In [55]:
a

array([10, 11, 12, 13])

In [56]:
a+100

array([110, 111, 112, 113])

In [57]:
a+=100

In [58]:
a

array([110, 111, 112, 113])

In [59]:
l = [1,2,3,4]
[i * 10 for i in l]

[10, 20, 30, 40]

In [60]:
l

[1, 2, 3, 4]

In [61]:
b = np.array([10,10,10,10])

In [62]:
a + b

array([120, 121, 122, 123])

In [63]:
a * b

array([1100, 1110, 1120, 1130])

## Boolean arrays

In [64]:
a = np.arange(4)

In [65]:
a

array([0, 1, 2, 3])

In [67]:
a[[0, -1]]

array([0, 3])

In [68]:
a[[True,False,True,False]]

array([0, 2])

In [69]:
a >= 2

array([False, False,  True,  True])

In [70]:
a

array([0, 1, 2, 3])

In [71]:
a.mean()

1.5

In [72]:
a[a >= 2]

array([2, 3])

In [73]:
a[(a==0) | (a==1)]

array([0, 1])

In [75]:
A = np.random.randint(100, size=(3,3))

In [76]:
A

array([[50, 53, 40],
       [96, 27, 58],
       [22,  7, 89]])

In [77]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [78]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [79]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [80]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [81]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [83]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [84]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of objects in Memory

### Ints, floats

In [86]:
# An integer in Python is = 24Bytes
sys.getsizeof(0)

24

In [88]:
# longs are even larger
sys.getsizeof(10**100)

72

In [89]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [91]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [92]:
np.dtype(float).itemsize

8

### Lists are even larger

In [93]:
# A one-element list
sys.getsizeof([1])

64

In [94]:
# An arrays of one-element in numpy
np.array([1]).nbytes


4

### And Performance is also important

In [95]:
l = list(range(1000))

In [97]:
a = np.arange(1000)

In [98]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [99]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 635 µs


332833500

In [100]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

## Useful Numpy functions

### random

In [101]:
np.random.random(size=2)

array([0.9223441 , 0.89416625])

In [102]:
np.random.normal(size=2)

array([-0.32249576, -0.76147376])

In [103]:
np.random.rand(2,4)

array([[0.4945167 , 0.86871971, 0.61809048, 0.6567453 ],
       [0.92970538, 0.96414217, 0.33161222, 0.08258994]])

### arrange

In [104]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [106]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [108]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [109]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [110]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [111]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [112]:
np.linspace(0,1,20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])